In [ ]:
import pandas as pd
from google.colab import files
uploaded = files.upload()

# creating a dictionory on data given by maa'm
data = {
    'Name': ['James', 'Barra', 'Sarah', 'Bill', 'Peter', 'Chloe', 'Ben', 'Anna'],
    'Gender': ['Male', 'Male', 'Female', 'Male', 'Male', 'Female', 'Male', 'Female'],
    'Age': [27, 32, 34, 23, 27, 32, 34, 23],
    'Weight': [75.1, 98.3, 63.5, 87.2, 75.1, 98.3, 63.5, 87.2],
    'Height': ['Short', 'Short', 'Medium', 'Tall', 'Tall', 'Short', 'Medium', 'Tall']
}

Saving adult.csv to adult (1).csv

In [ ]:
#creating a DataFrame using pandas.DataFrame() method by provideing crated dict
df = pd.DataFrame(data)
print(df)

    Name  Gender  Age  Weight  Height
0  James    Male   27    75.1   Short
1  Barra    Male   32    98.3   Short
2  Sarah  Female   34    63.5  Medium
3   Bill    Male   23    87.2    Tall
4  Peter    Male   27    75.1    Tall
5  Chloe  Female   32    98.3   Short
6    Ben    Male   34    63.5  Medium
7   Anna  Female   23    87.2    Tall

In [ ]:
# display all columns
df.columns

Index(['Name', 'Gender', 'Age', 'Weight', 'Height'], dtype='object')

In [ ]:
# display the information about DataFrame such as Column , Non-null count , Datatypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      object
 1   Gender  8 non-null      object
 2   Age     8 non-null      int64
 3   Weight  8 non-null      float64
 4   Height  8 non-null      object
dtypes: float64(1), int64(1), object(3)
memory usage: 448.0+ bytes

In [ ]:
#creating a new column and asssigning all values of that column to null
df['country'] = None
print(df)

    Name  Gender  Age  Weight  Height country
0  James    Male   27    75.1   Short    None
1  Barra    Male   32    98.3   Short    None
2  Sarah  Female   34    63.5  Medium    None
3   Bill    Male   23    87.2    Tall    None
4  Peter    Male   27    75.1    Tall    None
5  Chloe  Female   32    98.3   Short    None
6    Ben    Male   34    63.5  Medium    None
7   Anna  Female   23    87.2    Tall    None

In [ ]:
# describe method generates the statistical information about the dataFrame
df.describe()

             Age     Weight
count   8.000000   8.000000
mean   29.000000  81.025000
std     4.598136  13.926209
min    23.000000  63.500000
25%    26.000000  72.200000
50%    29.500000  81.150000
75%    32.500000  89.975000
max    34.000000  98.300000

In [ ]:
# returns total number of cells in DataFrame
print(df.size)

48

In [ ]:
# return the number of dimention of DataFrame (this will always be 2 if its a data frame)
df.ndim

2

In [ ]:
# display true if column value is null(None) else display flase
df.isnull()

    Name  Gender    Age  Weight  Height  country
0  False   False  False   False   False     True
1  False   False  False   False   False     True
2  False   False  False   False   False     True
3  False   False  False   False   False     True
4  False   False  False   False   False     True
5  False   False  False   False   False     True
6  False   False  False   False   False     True
7  False   False  False   False   False     True

In [ ]:
# return count of null values in each column
df.isnull().sum()

Name       0
Gender     0
Age        0
Weight     0
Height     0
country    8
dtype: int64

In [ ]:
# return true if there is any null value in DataFrame
df.isnull().values.any()

True

In [ ]:
print(df['country'].isnull())

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
Name: country, dtype: bool

In [ ]:
# fillna method fills the null values with provided value , we can set the limits on changing values
df.fillna("india",inplace=True,limit = 5)

In [ ]:
print(df)

    Name  Gender  Age  Weight  Height country
0  James    Male   27    75.1   Short   india
1  Barra    Male   32    98.3   Short   india
2  Sarah  Female   34    63.5  Medium   india
3   Bill    Male   23    87.2    Tall   india
4  Peter    Male   27    75.1    Tall   india
5  Chloe  Female   32    98.3   Short    None
6    Ben    Male   34    63.5  Medium    None
7   Anna  Female   23    87.2    Tall    None

In [ ]:
# loc method insert the row at given location , follows 0 base indexing
df.loc[len(df)] = ["Om" , "Male", 20 , None , "Tall" ,  None]
df.loc[len(df)] = ["Abhi" , "Male", 21 , None , "short" ,  None]

<ipython-input-103-6a8578f10bd7>:2: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df.loc[len(df)] = ["Om" , "Male", 20 , None , "Tall" ,  None]
<ipython-input-103-6a8578f10bd7>:3: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df.loc[len(df)] = ["Abhi" , "Male", 21 , None , "short" ,  None]

In [ ]:
print(df)

    Name  Gender  Age  Weight  Height country
0  James    Male   27    75.1   Short   india
1  Barra    Male   32    98.3   Short   india
2  Sarah  Female   34    63.5  Medium   india
3   Bill    Male   23    87.2    Tall   india
4  Peter    Male   27    75.1    Tall   india
5  Chloe  Female   32    98.3   Short    None
6    Ben    Male   34    63.5  Medium    None
7   Anna  Female   23    87.2    Tall    None
8     Om    Male   20     NaN    Tall    None
9   Abhi    Male   21     NaN   short    None

In [ ]:
# mean() returns the statistical mean of a given column
mean_age = df['Age'].mean()
print(mean_age)

27.3

In [ ]:
# mode() returns the statistical mode of a given column
mode_age = df['Age'].mode()
print(mode_age)

0    23
1    27
2    32
3    34
Name: Age, dtype: int64

In [ ]:
# median() returns the statistical median of a given column
median_age = df['Age'].median()
print(median_age)

27.0

In [ ]:
# drops the row with null values
df.dropna()

    Name  Gender  Age  Weight  Height country
0  James    Male   27    75.1   Short   india
1  Barra    Male   32    98.3   Short   india
2  Sarah  Female   34    63.5  Medium   india
3   Bill    Male   23    87.2    Tall   india
4  Peter    Male   27    75.1    Tall   india

In [ ]:
print(df)

    Name  Gender  Age  Weight  Height country
0  James    Male   27    75.1   Short   india
1  Barra    Male   32    98.3   Short   india
2  Sarah  Female   34    63.5  Medium   india
3   Bill    Male   23    87.2    Tall   india
4  Peter    Male   27    75.1    Tall   india
5  Chloe  Female   32    98.3   Short    None
6    Ben    Male   34    63.5  Medium    None
7   Anna  Female   23    87.2    Tall    None
8     Om    Male   20     NaN    Tall    None
9   Abhi    Male   21     NaN   short    None

In [ ]:
# make changes on original dataFrame
df.dropna(inplace = True)

In [ ]:
print(df)

    Name  Gender  Age  Weight  Height country
0  James    Male   27    75.1   Short   india
1  Barra    Male   32    98.3   Short   india
2  Sarah  Female   34    63.5  Medium   india
3   Bill    Male   23    87.2    Tall   india
4  Peter    Male   27    75.1    Tall   india

In [ ]:
# inserting 2 duplicate records
df.loc[len(df)] = ["Anna" , "Female", 23 , 87.2 , "Tall" ,  "india"]
df.loc[len(df)] = ["Anna" , "Female", 23 , 87.2 , "Tall" ,  "india"]

In [ ]:
print(df)

    Name  Gender  Age  Weight  Height country
0  James    Male   27    75.1   Short   india
1  Barra    Male   32    98.3   Short   india
2  Sarah  Female   34    63.5  Medium   india
3   Bill    Male   23    87.2    Tall   india
4  Peter    Male   27    75.1    Tall   india
5   Anna  Female   23    87.2    Tall   india
6   Anna  Female   23    87.2    Tall   india

In [ ]:
# true if row has duplicates
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [ ]:
# if keep = last is set . keep the last record as non duplicate otherwise all are duplicates
df.duplicated(keep='last')

0    False
1    False
2    False
3    False
4    False
5     True
6    False
dtype: bool

In [ ]:
# prints first 5 records (5 is a default value)
df.head()

    Name  Gender  Age  Weight  Height country
0  James    Male   27    75.1   Short   india
1  Barra    Male   32    98.3   Short   india
2  Sarah  Female   34    63.5  Medium   india
3   Bill    Male   23    87.2    Tall   india
4  Peter    Male   27    75.1    Tall   india

In [ ]:
df.head(2)

    Name Gender  Age  Weight Height country
0  James   Male   27    75.1  Short   india
1  Barra   Male   32    98.3  Short   india

In [ ]:
# prints last 5 records
df.tail()

    Name  Gender  Age  Weight  Height country
2  Sarah  Female   34    63.5  Medium   india
3   Bill    Male   23    87.2    Tall   india
4  Peter    Male   27    75.1    Tall   india
5   Anna  Female   23    87.2    Tall   india
6   Anna  Female   23    87.2    Tall   india

In [ ]:
df.tail(2)

   Name  Gender  Age  Weight Height country
5  Anna  Female   23    87.2   Tall   india
6  Anna  Female   23    87.2   Tall   india

In [ ]:
# creating dataframe on data inside csv file using read_csv method to read data into dataframe variable
new_df = pd.read_csv('adult.csv')

In [ ]:
# display first 5 records
new_df.tail()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
# display all columns
new_df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'educational-num',
       'marital-status', 'occupation', 'relationship', 'race', 'gender',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

In [ ]:
# display the information about DataFrame such as Column , Non-null count , Datatypes
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

In [ ]:
#creating a new column and asssigning all values of that column to null
new_df['fav sports'] = None
new_df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,fav sports
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K,None
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K,None
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K,None
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K,None
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K,None

In [ ]:
# describe method generates the statistical information about the dataFrame
new_df.describe()

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
count,48842.000000,4.884200e+04,48842.000000,48842.000000,48842.000000,48842.000000
mean,38.643585,1.896641e+05,10.078089,1079.067626,87.502314,40.422382
std,13.710510,1.056040e+05,2.570973,7452.019058,403.004552,12.391444
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.175505e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781445e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.376420e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

In [ ]:
# returns total number of cells in DataFrame
print(new_df.size)

781472

In [ ]:
# return the number of dimention of DataFrame (this will always be 2 if its a data frame)
new_df.ndim

2

In [ ]:
# display true if column value is null(None) else display flase
new_df.head().isnull()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,fav sports
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True

In [ ]:
# return count of null values in each column
new_df.isnull().sum()

age                    0
workclass              0
fnlwgt                 0
education              0
educational-num        0
marital-status         0
occupation             0
relationship           0
race                   0
gender                 0
capital-gain           0
capital-loss           0
hours-per-week         0
native-country         0
income                 0
fav sports         48842
dtype: int64

In [ ]:
# return true if there is any null value in DataFrame
new_df.isnull().values.any()

True

In [ ]:
# fillna method fills the null values with provided value , we can set the limits on changing values
new_df.fillna("cricket",inplace=True,limit = 48800)

In [ ]:
# loc method insert the row at given location , follows 0 base indexing
new_df.loc[len(new_df)] = [25	,"Private", 226802,	"11th" ,	7	, "Never-married" ,	"Machine-op-inspct"	, "Own-child" , "Black" , "Male" , 0 , 0 , 40 ,	"United-States" ,	"<=50K" ,	"cricket"]
new_df.loc[len(new_df)] = [25	,"Private", 226802,	"11th" ,	7	, "Never-married" ,	"Machine-op-inspct"	, "Own-child" , "Black" , "Male" , 0 , 0 , 40 ,	"United-States" ,	"<=50K" ,	"cricket"]

In [ ]:
new_df.tail()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,fav sports
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K,None
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K,None
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K,None
48842,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K,cricket
48843,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K,cricket

In [ ]:
# mean() returns the statistical mean of a given column
mean_age = new_df['age'].mean()
print(mean_age)

38.64302677913357

In [ ]:
# mode() returns the statistical mode of a given column
mode_age = new_df['age'].mode()
print(mode_age)

0    36
Name: age, dtype: int64

In [ ]:
# median() returns the statistical median of a given column
median_age = new_df['age'].median()
print(median_age)

37.0

In [ ]:
# drops the row with null values
new_df.dropna()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,fav sports
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K,cricket
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K,cricket
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K,cricket
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K,cricket
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K,cricket
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48802,33,Private,273243,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,Black,Male,0,0,40,United-States,<=50K,cricket
48803,58,Private,147707,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,40,United-States,<=50K,cricket
48804,30,Private,77266,HS-grad,9,Divorced,Transport-moving,Not-in-family,White,Male,0,0,55,United-States,<=50K,cricket
48842,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K,cricket
48843,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K,cricket

In [ ]:
# make changes on original dataFrame
df.dropna(inplace = True)

In [ ]:
# true if row has duplicates
new_df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
48841    False
48842     True
48843     True
48844     True
48845     True
Length: 48846, dtype: bool

In [ ]:
# if keep = last is set . keep the last record as non duplicate otherwise all are duplicates
new_df.duplicated(keep='last')

0         True
1        False
2        False
3        False
4        False
         ...
48841    False
48842     True
48843     True
48844     True
48845    False
Length: 48846, dtype: bool

In [ ]:
# prints first 5 records (5 is a default value)
new_df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,fav sports
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K,cricket
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K,cricket
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K,cricket
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K,cricket
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K,cricket

In [ ]:
# drops the row with null values
new_df.dropna(inplace=True)

In [ ]:
new_df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,fav sports
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K,cricket
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K,cricket
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K,cricket
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K,cricket
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K,cricket

In [ ]:
new_df.tail()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,fav sports
48804,30,Private,77266,HS-grad,9,Divorced,Transport-moving,Not-in-family,White,Male,0,0,55,United-States,<=50K,cricket
48842,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K,cricket
48843,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K,cricket
48844,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K,cricket
48845,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K,cricket